### ISSUE TITLE
Restore negative depths

### ISSUE THREAD

**Issue by jb388** [powellcenter-soilcarbon/soilcarbon#8]
In Yujie's original database the organic layers are entered as negative values, while the mineral soil layers are positive (i.e. 0 = mineral soil surface). Lines 62:63 of the 'readYujie' function convert the depths to absolute values. If the 'abs' function is removed this should fix this issue.

**Comment by greymonroe** [comment]
fixed in last push

**Comment by greymonroe** [comment]
Thank you for finding this and bringing it to my attention! 

I removed the abs() call to layers in the readYujie() and have updated the database in the package.
